### ISSUE TITLE
'hsb' was not declared in this scope

### ISSUE THREAD

**Issue by eliabieri** [probonopd/ESP8266HueEmulator#10]
when I try to compile the sketch I get the following error:
ESP8266HueEmulator:550: error: 'hsb' was not declared in this scope
'HsbColor' does not name a type

I`m on Arduino 1.6.4 and I use the arduino-esp version on july 23th

**Comment by probonopd** [comment]
Then possibly your NeoPixelBus library is outdated.The NeoPixelAnimator branch has the HsbColor object.

**Comment by eliabieri** [comment]
I pulled the latest version from https://github.com/Makuna/NeoPixelBus but the error stays

**Comment by probonopd** [comment]
Are you sure you have the NeoPixelAnimator branch?

**Comment by eliabieri** [comment]
It now compiles. Thanks
