### ISSUE TITLE
Any chance to use ESP8266 as multiple lamps or strips without the emulated bridge ?

### ISSUE THREAD

**Issue by MopheusDG** [probonopd/ESP8266HueEmulator#101]
I was wondering, as I already own a HUE Bridge 2.0, can we extract part of the code to build simple "lamps" or "strips" that are detectable on an original philips bridge ?
As I own a bridge, I'd love to be able to add my own RGB Lamps (That I don't have as they are too expensive), built with an ESP.
Using the new Razer Synapse 3 software, it could be nice to use an ESP8266 to drive 3 or 4 generic RGB leds or RGB  led strips and use it as some kind of ambilight. And that could be much easier to do, right ?

**Comment by xYoshiox** [comment]
I know that this is a github for development but I found this: https://www.amazon.com/Wireless-electronic-ballast-interface-certified/dp/B00NMSQ4QQ

Maybe if someone can buy it an reverse engineering that....

**Comment by mariusmotea** [comment]
Hue bridge communicate just with ZigBee lights,. Esp8266 work with wifi protocol.w

**Comment by gibman** [comment]
The biggest concern with multiple bridges are the imposed limitations on some of the hue software.
eg. the official philips hue android can only handle one bridge.

then there is "all 4 hue" on android also.. it supports multiple bridges just fine.

**Comment by MopheusDG** [comment]
I'm not sure but from what I've seen, the Razer application for Windows does not allow either, cause it can only see my original Bridge, not the emulated one.
