### ISSUE TITLE
Can't compile, Flush error

### ISSUE THREAD

**Issue by psgoral** [probonopd/ESP8266HueEmulator#103]
Hi. I want to compile code and upload to Nodemcu. I have this error:

In file included from D:\Downloads\ESP8266HueEmulator-master\ESP8266HueEmulator-master\ESP8266HueEmulator\ESP8266HueEmulator.ino:19:0:

C:\Users\icego\Documents\Arduino\libraries\aJson-master/aJSON.h:90:6: error: conflicting return type specified for 'virtual int aJsonStream::flush()'

  int flush();

      ^

In file included from C:\Users\icego\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\cores\esp8266/Stream.h:26:0,

                 from C:\Users\icego\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\cores\esp8266/HardwareSerial.h:31,

                 from C:\Users\icego\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\cores\esp8266/Arduino.h:246,

                 from sketch\ESP8266HueEmulator.ino.cpp:1:

C:\Users\icego\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\cores\esp8266/Print.h:93:22: error:   overriding 'virtual void Print::flush()'

         virtual void flush() { /* Empty implementation for backward compatibility */ }

                      ^

exit status 1
Błąd kompilacji dla płytki NodeMCU 1.0 (ESP-12E Module).

Any ideas? IDE 1.8.5

**Comment by xYoshiox** [comment]
Go to the board manager and make sure that you are using version 2.3 for the ESP8266.
