### ISSUE TITLE
Can't compile code

### ISSUE THREAD

**Issue by EgeSS** [probonopd/ESP8266HueEmulator#106]

**Comment by EgeSS** [comment]
The error that i get is:
Arduino: 1.8.5 (Mac OS X), Board: "WeMos D1 R2 & mini, 80 MHz, 4M (1M SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 230400"

In file included from /Users/egetunali/ESP8266HueEmulator/ESP8266HueEmulator/ESP8266HueEmulator.ino:19:0:
/Users/egetunali/Arduino/libraries/aJson/aJSON.h:92:6: error: conflicting return type specified for 'virtual int aJsonStream::flush()'
  int flush();
      ^
In file included from /Users/egetunali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/Stream.h:26:0,
                 from /Users/egetunali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/HardwareSerial.h:31,
                 from /Users/egetunali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/Arduino.h:246,
                 from sketch/ESP8266HueEmulator.ino.cpp:1:
/Users/egetunali/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/Print.h:93:22: error:   overriding 'virtual void Print::flush()'
         virtual void flush() { /* Empty implementation for backward compatibility */ }
                      ^
exit status 1
Error compiling for board WeMos D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

I've tried everything i could but i still can't compile the code.Can you please help me?

**Comment by itsamaik** [comment]
Same problem here. I've tried to see if we could use different versions of the used libraries, but it seems like the latest commit was on this repo.

**Comment by EgeSS** [comment]
I've actually fixed the issue by opening "Tools/Boards Manager/esp8266/uninstall/install version 2.3.0
