### ISSUE TITLE
What Hardware is supported

### ISSUE THREAD

**Issue by Dylantje** [probonopd/ESP8266HueEmulator#11]
Dear...
Great peace of work!!!!!!

My problem, what Hardware do i need.
Can i switch a regular white or rgb ledstrip to, when i am fine to now that this not the same color like HUE
There are more esp8266 version will this work on all?
And perhaps you have other idea's what i can buy in China...

**Comment by probonopd** [comment]
All WS2812B based LEDs should work, and all ESP modules (for experimenting I can recommend the NodeMCU 1.0 board and for permanent installation the ESP-12E if you like to solder).

![nodemcu1](https://cloud.githubusercontent.com/assets/2480569/8914842/c6a31e2e-34a1-11e5-8358-657fe22d583b.jpg)

**Comment by Dylantje** [comment]
Thanks for the fast support...!! [ Now i can order in China ]
And my question abbot the regular rgb or white led?
Are they switching from the hue bridge or not, do you think?
I will give it a try, when you think it is possible..[ without warranty! ]
 I would be too crazy that I can switch an LED via the hue bridge, [ waterproof rgb led for in the garden!!] :+1: :-)

**Comment by probonopd** [comment]
Have you ever seen a WS2812B based white LED? I haven't...

By the way, my code emulates the Bridge. So you don't need a Bridge. The app talks to the ESP directly without the need for a Bridge.

**Comment by Dylantje** [comment]
sorry for my stupidity...
Only can the code not talk with the/a bridge? That would give more options for me.

Thanks for your patience

**Comment by probonopd** [comment]
No, this code *is* the Bridge.
(Talking *to* the bridge is what the existing client apps do.)
