### ISSUE TITLE
"#pragma once" in LightService.h

### ISSUE THREAD

**Issue by ChrisHanuta** [probonopd/ESP8266HueEmulator#110]
Hello, 
I would like to use LightSevice.h as a libary in my own project. 
Can you add that
#pragma once
or add the old one
#ifndef LightSevice_h
#define LightSevice_h
...
#endif / * LightSevice_h * /

So that the class can include in more than one file.

LG

**Comment by probonopd** [comment]
Please send a [pull request](https://help.github.com/articles/creating-a-pull-request/), thanks.

**Comment by ChrisHanuta** [comment]
pull request has been sent
