### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by krulkip** [probonopd/ESP8266HueEmulator#12]
I am getting an error compiling. The error is described here.
https://github.com/esp8266/Arduino/issues/612
What setup are you using to avoid this.
I am also getting a waring which i get rid of by adding this near the top.
// gets rid of annoying "deprecated conversion from string constant blah blah" warning
#pragma GCC diagnostic ignored "-Wwrite-strings"

**Comment by probonopd** [comment]
I am using esp8266/Arduino from git. I am using this specific version: `git reset --hard 1154545fa8db7f1ce183865b776cadffc4e8d03f`. Not sure whether this makes a difference.

**Comment by krulkip** [comment]
Installed this libm.a and compiled fine after that.
https://files.gitter.im/esp8266/Arduino/Abqa/libm.a.tbz
