### ISSUE TITLE
iOS Hue app causes reboot

### ISSUE THREAD

**Issue by sticilface** [probonopd/ESP8266HueEmulator#14]
Seems to cause reboots consistently, whenever the brightness is altered.  

Looking at the serial output, it seems to receive requests constantly when the brightness slider is moved, until it hits the "You need to use a newer version of the ESP826" line and then it reboots. 

It works fine for the chroma app on the mac?

Any ideas?

**Comment by sticilface** [comment]
Got somewhere.

1)  Instead of continuing with the web function when plain == "", place a return there.  This stops it from crashing when an incorrect / empty request is parsed...  

2)  now I get to see what is passed from the iOS app, and it is XY colour space so this is used.  hope this helps


```
===
79927, heap = 31856
requestedUri: /api/4J5y4l5ZRXIiWS2u/lights/1/state Method = 3
{
  "bri" : 185,
  "xy" : [
    0.1587891,
    0.2467008
  ],
  "on" : true
}
Number of the light --> 0
Retrieved saved HSB
H=0.00
S=0.00
B=0.73
Running hsb2rgb
2.: Convert to H, S, L
3.: Convert to RgbColor
Running rgb2hsb
1.: H, S, B
2.: Convert to hue, sat, bri
79928
{"1":{"type":"Extended color light","name":"Hue LightStrips 1","modelid":"LST001","state":{"on":true,"hue":0.00000,"bri":184.00000,"sat":0.00000,"xy":[0.00000,0.00000],"ct":500,"alert":"none","effect":"none","colormode":"hs","reachable":true}}}
I should --> 1
79958
===
```

**Comment by probonopd** [comment]
My code is somewhat outdated, @me-no-dev had been working on a greatly improved version. Please contact him, he is also on Gitter.im -- probably it makes most sense to start off from his version. Pull requests welcome.

**Comment by probonopd** [comment]
@sticilface is this still an issue in the latest version? Couldn't reproduce.

**Comment by sticilface** [comment]
i couldn't say.  i've not worked on this for months...  
the whole hue ecosystem is not so useful with my application, as it has monster overhead, so i developed my own instead!

**Comment by probonopd** [comment]
Thanks @sticilface. Please reopen if this is still an issue.
