### ISSUE TITLE
Can't compile too

### ISSUE THREAD

**Issue by roman-rv** [probonopd/ESP8266HueEmulator#21]
Arduino: 1.6.8 Hourly Build 2015/12/23 04:43 (Windows 7), Плата:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino: In function 'void handleAllOthers()':
HueEmulator:81: error: 'addConfigJson' was not declared in this scope
     addConfigJson(root);
                       ^
HueEmulator:96: error: 'addConfigJson' was not declared in this scope
     addConfigJson(config);
                         ^
HueEmulator:100: error: 'addLightJson' was not declared in this scope
       addLightJson(lights, i, StripRgbColors[i-1]);
                                                  ^
HueEmulator:112: error: 'subStr' was not declared in this scope
     client = subStr(requestedUri.c_str(), "/", 1);
                                                 ^
HueEmulator:131: error: 'subStr' was not declared in this scope
     int numberOfTheLight = atoi(subStr(requestedUri.c_str(), "/", 4)) - 1; // The number of the light to be switched; they start with 1
                                                                    ^
HueEmulator:165: error: 'hsb2rgb' was not declared in this scope
     rgb = hsb2rgb(hue, sat, bri);
                                ^
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino: In lambda function:
HueEmulator:181: error: no matching function for call to 'HslColor::LinearBlend(const HslColor&, const RgbColor&, const float&)'
         HslColor updatedColor = HslColor::LinearBlend(originalColor, rgb, param.progress);
                                                                                        ^
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino:181:89: note: candidate is:
In file included from C:\Users\Администратор\Documents\Arduino\libraries\NeoPixelBus-master\src/NeoPixelBus.h:33:0,
                 from C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino:17:
C:\Users\Администратор\Documents\Arduino\libraries\NeoPixelBus-master\src/internal/HslColor.h:67:55: note: template<class T_NEOHUEBLEND> static HslColor HslColor::LinearBlend(const HslColor&, const HslColor&, float)
     template <typename T_NEOHUEBLEND> static HslColor LinearBlend(const HslColor& left,
                                                       ^
C:\Users\Администратор\Documents\Arduino\libraries\NeoPixelBus-master\src/internal/HslColor.h:67:55: note:   template argument deduction/substitution failed:
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino:181:89: note:   couldn't deduce template parameter 'T_NEOHUEBLEND'
         HslColor updatedColor = HslColor::LinearBlend(originalColor, rgb, param.progress);
                                                                                         ^
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino: In lambda function:
HueEmulator:192: error: no matching function for call to 'HslColor::LinearBlend(const HslColor&, RgbColor&, const float&)'
         HslColor updatedColor = HslColor::LinearBlend(originalColor, black, param.progress);
                                                                                           ^
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino:192:91: note: candidate is:
In file included from C:\Users\Администратор\Documents\Arduino\libraries\NeoPixelBus-master\src/NeoPixelBus.h:33:0,
                 from C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino:17:
C:\Users\Администратор\Documents\Arduino\libraries\NeoPixelBus-master\src/internal/HslColor.h:67:55: note: template<class T_NEOHUEBLEND> static HslColor HslColor::LinearBlend(const HslColor&, const HslColor&, float)
     template <typename T_NEOHUEBLEND> static HslColor LinearBlend(const HslColor& left,
                                                       ^
C:\Users\Администратор\Documents\Arduino\libraries\NeoPixelBus-master\src/internal/HslColor.h:67:55: note:   template argument deduction/substitution failed:
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino:192:91: note:   couldn't deduce template parameter 'T_NEOHUEBLEND'
         HslColor updatedColor = HslColor::LinearBlend(originalColor, black, param.progress);
                                                                                           ^
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino: In function 'void handleAllOthers()':
HueEmulator:201: error: 'addLightJson' was not declared in this scope
     addLightJson(root, numberOfTheLight + 1, rgb); // FIXME: This does not give the new color while an animation is still running
                                                 ^
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino: In function 'void setup()':
HueEmulator:234: error: 'infoLight' was not declared in this scope
   infoLight(white);
                  ^
HueEmulator:248: error: 'StringIPaddress' was not declared in this scope
   ipString = StringIPaddress(WiFi.localIP());
                                            ^
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino: In function 'void loop()':
HueEmulator:298: error: no matching function for call to 'NeoPixelAnimator::UpdateAnimations(int)'
     if ( animator.IsAnimating() ) animator.UpdateAnimations(100);
                                                                ^
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino:298:64: note: candidate is:
In file included from C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino:18:0:
C:\Users\Администратор\Documents\Arduino\libraries\NeoPixelBus-master\src/NeoPixelAnimator.h:110:10: note: void NeoPixelAnimator::UpdateAnimations()
     void UpdateAnimations();
          ^
C:\Users\Администратор\Documents\Arduino\libraries\NeoPixelBus-master\src/NeoPixelAnimator.h:110:10: note:   candidate expects 0 arguments, 1 provided
C:\Download\PhilipsTV\esp2866hueEmulator\HueEmulator\HueEmulator.ino: In function 'void addLightJson(aJsonObject*, int, RgbColor)':
HueEmulator:388: error: 'rgb2hsb' was not declared in this scope
   HsbColor hsb = rgb2hsb(rgb);
                             ^
exit status 1
'addConfigJson' was not declared in this scope

**Comment by probonopd** [comment]
Did you install [aJson](https://github.com/interactive-matter/aJson.git)? Anyhow, #18 blocks compilation at the moment.

**Comment by roman-rv** [comment]
> Did you install aJson? Anyhow, #18 blocks compilation at the moment.
Yes. Sketches of aJson example compiles fine

**Comment by probonopd** [comment]
I can compile fine with the following steps:

* I used [Arduino-1.6.11.hourly201608161225.esp497d19d-x86_64.AppImage](https://bintray.com/probono/AppImages/Arduino#files) which comes with the latest versions of both the Arduino IDE and esp8266/Arduino ready-to-use
* In the Arduino IDE, Open the Library Manager and search for "NeoPixelBus by Makuna" and install
* Download https://github.com/interactive-matter/aJson/archive/master.zip and install the library via the Arduino IDE
* Edit the sketch to contain your WLAN credentials
* Compile

**Comment by roman-rv** [comment]
Thanx, i will try
