### ISSUE TITLE
Help Me pls

### ISSUE THREAD

**Issue by spindi93** [probonopd/ESP8266HueEmulator#22]
Arduino: 1.6.9 (Mac OS X), Board: "Generic ESP8266 Module, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS), ck, Disabled, None"

/Users/Manuel/Downloads/ESP8266HueEmulator-master/ESP8266HueEmulator/ESP8266HueEmulator.ino: In function 'void loop()':
ESP8266HueEmulator:297: error: no matching function for call to 'NeoPixelAnimator::UpdateAnimations(int)'
     if ( animator.IsAnimating() ) animator.UpdateAnimations(100);
                                                                ^
/Users/Manuel/Downloads/ESP8266HueEmulator-master/ESP8266HueEmulator/ESP8266HueEmulator.ino:297:64: note: candidate is:
In file included from /Users/Manuel/Downloads/ESP8266HueEmulator-master/ESP8266HueEmulator/ESP8266HueEmulator.ino:18:0:
/Users/Manuel/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/NeoPixelAnimator.h:110:10: note: void NeoPixelAnimator::UpdateAnimations()
     void UpdateAnimations();
          ^
/Users/Manuel/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/NeoPixelAnimator.h:110:10: note:   candidate expects 0 arguments, 1 provided
exit status 1
no matching function for call to 'NeoPixelAnimator::UpdateAnimations(int)'

Can you Help me pls?

**Comment by probonopd** [comment]
I think this code has to be refactored to cater for the changes in NeoPixelBus. Currently I don't have the time to do it, sorry.
