### ISSUE TITLE
ESP2866 Lib Ardunio IDE

### ISSUE THREAD

**Issue by dlevitryon** [probonopd/ESP8266HueEmulator#33]
What ESP2866 Lib are we all using? For some reason it errors out when compiling, saying ESP2866 Generic is not supported. Which ESP2866 Board are you guys working with? Thanks!

**Comment by probonopd** [comment]
I have mainly been using ESP-12E and NodeMCU 1.0

**Comment by richms** [comment]
I have it working on a wemos D1 - the full sized one, which has I think an esp-12 or 12e on it. Using wemos D1 retired in the board manager of the current arduino IDE.
