### ISSUE TITLE
Travis CI compilation fails

### ISSUE THREAD

**Issue by probonopd** [probonopd/ESP8266HueEmulator#35]
Travis CI compilation is broken with the following error:

```
########################################################################

SWITCHING TO esp8266: ✓

########################################################################

ESP8266HueEmulator.ino: ✖

----------------------------- DEBUG OUTPUT -----------------------------

Picked up JAVA_TOOL_OPTIONS: 

Loading configuration...

Xlib:  extension "RANDR" missing on display ":1.0".

Initializing packages...

Preparing boards...

Verifying...

In file included from /home/travis/arduino_ide/libraries/NeoPixelBus/src/NeoPixelBus.h:77:0,

                 from ESP8266HueEmulator.ino:7:

/home/travis/arduino_ide/libraries/NeoPixelBus/src/internal/DotStarSpiMethod.h:29:17: fatal error: SPI.h: No such file or directory

 #include <SPI.h>

                 ^

compilation terminated.

Error compiling.

------------------------------------------------------------------------
```

Will not merge any PRs until this can be resolved, because I always want to have a state of the repository that is known to build at least on Travis CI.

The state of the repository as it is now built successfully 2 months ago in https://travis-ci.org/probonopd/ESP8266HueEmulator/builds/155632821.

**Comment by tinwhisker** [comment]
Looks like the NeoPixel library updated, and the native SPI library is missing.

Quick/dirty fix:
https://github.com/Makuna/NeoPixelBus/tree/2.1.4

Or add this library set as a dependancy:
https://github.com/ninjablocks/arduino

Or just install the SPI lib.

**Comment by probonopd** [comment]
Thanks, that did the trick @tinwhisker
