### ISSUE TITLE
fatal error: TimeLib.h: No such file or directory

### ISSUE THREAD

**Issue by jdschuitemaker** [probonopd/ESP8266HueEmulator#71]
I just downloaded the latest version and I I am seeing this error when I verify it:

`D:\Development\ESP8266 Arduino\Sketches\ESP8266HueEmulator-master\ESP8266HueEmulator\ESP8266HueEmulator.ino:10:21: fatal error: TimeLib.h: No such file or directory

 #include <TimeLib.h>

                     ^

compilation terminated.

exit status 1
Error compiling for board WeMos D1 R2 & mini.`

How can I solve this?

**Comment by probonopd** [comment]
Did you follow all the steps from https://github.com/probonopd/ESP8266HueEmulator#compilation?

**Comment by jdschuitemaker** [comment]
No, didn't do that. Now I have done that it works. Thanks for the hint...

**Comment by micheljung** [comment]
I did follow the steps, but my Arduino Sketchbook location was set to `C:\Users\<User>\Documents\Arduino` instead of `C:\Users\<User>\Arduino`. Moving the libraries folder to the correct location fixed the problem.

In case someone has the same issue.

**Comment by probonopd** [comment]
Thanks for the hint @micheljung

**Comment by Carsonyjk** [comment]
@probonopd 
I had the same problem. you said I need follow all the steps from https://github.com/probonopd/ESP8266HueEmulator#compilation? ,

mkdir -p $HOME/Arduino/libraries/
cd $HOME/Arduino/libraries/
git clone --branch 2.1.4 https://github.com/Makuna/NeoPixelBus.git
git clone https://github.com/interactive-matter/aJson.git
git clone https://github.com/PaulStoffregen/Time.git
git clone https://github.com/gmag11/NtpClient.git
sed -i -e 's|#define PRINT_BUFFER_LEN 256|#define PRINT_BUFFER_LEN 4096|g'  aJson/aJSON.h
cd -
git clone https://github.com/probonopd/ESP8266HueEmulator.git
sed -i -e 's|#include "/secrets.h"|//#include "/secrets.h"|g' ESP8266HueEmulator/ESP8266HueEmulator/ESP8266HueEmulator.ino
sed -i -e 's|//const char|const char|g' ESP8266HueEmulator/ESP8266HueEmulator/ESP8266HueEmulator.ino

 I don't understand how to follow the steps, could you please explain in detail?

**Comment by Carsonyjk** [comment]
Hello all, I am using NodeMCU and RTC try to get current time, I had the same issue as jdschuitemaker, and I had read Probonopd's comment, however, I don't understand how to follow the steps below? Could somebody explain it in details? Thank you.
mkdir -p $HOME/Arduino/libraries/
cd $HOME/Arduino/libraries/
git clone --branch 2.1.4 https://github.com/Makuna/NeoPixelBus.git
git clone https://github.com/interactive-matter/aJson.git
git clone https://github.com/PaulStoffregen/Time.git
git clone https://github.com/gmag11/NtpClient.git
sed -i -e 's|#define PRINT_BUFFER_LEN 256|#define PRINT_BUFFER_LEN 4096|g'  aJson/aJSON.h
cd -
git clone https://github.com/probonopd/ESP8266HueEmulator.git
sed -i -e 's|#include "/secrets.h"|//#include "/secrets.h"|g' ESP8266HueEmulator/ESP8266HueEmulator/ESP8266HueEmulator.ino
sed -i -e 's|//const char|const char|g' ESP8266HueEmulator/ESP8266HueEmulator/ESP8266HueEmulator.ino

**Comment by Carsonyjk** [comment]
Hello, I fixed it by downloading the latest blynk library.
Thanks
