### ISSUE TITLE
ESP Client

### ISSUE THREAD

**Issue by t1m02k16** [probonopd/ESP8266HueEmulator#78]
Is there a possibility to use an esp as a client?

**Comment by probonopd** [comment]
Possibly, if you write a Hue client for ESP... If you don't necessarily need the (bloated) Hue protocol, check out the https://github.com/sticilface/Melvanimate project which can do server and client on ESP.

**Comment by t1m02k16** [comment]
Thanks, The problem is that I have lots of original hue lamps and also the bridge.
Wanted to expand me with ESP now .. Thought you would have synonymous.

**Comment by mariusmotea** [comment]
You can use home assistant that emulate a hue bridge and try to connect it to ESP8266HueEmulator i also have something similar but for the moment my hue bridge emulator work only with milight hub, ikea tradfri and ESP lights / sensors. I believe in about one week i will extend the support to control also hue bridge devices like in this project and they can be used as clients. In this mode SSDP service must be disabled somehow to not be automatically detected by the applications.
